#!/usr/bin/env bash
# Write frontend hosted environment from live Terraform outputs (post apply).
# Used by deploy-spa.sh and terraform-apply.yml so CloudFront always targets current API/Cognito.
set -euo pipefail

ROOT="$(CDPATH="" cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="${ROOT}/infra/terraform"
OUT="${ROOT}/frontend/src/environments/environment.hosted.generated.ts"
PROFILE="${AWS_PROFILE:-}"
if [[ -z ${PROFILE} && -z ${GITHUB_ACTIONS:-} && -z ${AWS_ACCESS_KEY_ID:-} ]]; then
	PROFILE="codeplatoon"
fi

aws_tf() {
	if [[ -n ${PROFILE} ]]; then
		AWS_PROFILE="${PROFILE}" "$@"
	else
		env -u AWS_PROFILE "$@"
	fi
}

cd "${TF_DIR}"
aws_tf terraform init -input=false >/dev/null
aws_tf terraform workspace select dev >/dev/null 2>&1 || aws_tf terraform workspace new dev >/dev/null

API_URL="$(aws_tf terraform output -raw api_endpoint)"
POOL_ID="$(aws_tf terraform output -raw cognito_user_pool_id)"
CLIENT_ID="$(aws_tf terraform output -raw cognito_spa_client_id)"
SPA_URL="$(aws_tf terraform output -raw spa_url 2>/dev/null || true)"
GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

if [[ -z ${API_URL} || ${API_URL} == null ]]; then
	echo "api_endpoint output empty — run terraform apply first" >&2
	exit 1
fi

mkdir -p "$(dirname "${OUT}")"
cat >"${OUT}" <<EOF
import { primeNgLicense } from './primeng-license';

/** Generated by scripts/sync-hosted-environment.sh at ${GENERATED_AT} — do not edit. */
export const environment = {
  production: true,
  composeDemo: false,
  apiBaseUrl: '${API_URL}',
  ragPath: '',
  agentPath: '/agent',
  historyPath: '/agent',
  demoTenantId: '',
  demoUserId: '',
  cognito: {
    region: 'us-east-1',
    userPoolId: '${POOL_ID}',
    clientId: '${CLIENT_ID}',
  },
  primeNgLicense,
};
EOF

echo "==> Wrote ${OUT}"
echo "    api=${API_URL}"
echo "    spa=${SPA_URL:-n/a}"
echo "    pool=${POOL_ID}"
